name: Deploy Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build website
        run: |
          yarn build

      - name: mv index
        run: |
          cd build/
          mv index.html index2.html
          cd ..

      - name: Compress build to zip
        run: |
          cd build/
          tar -czvf ../dist.tar.gz $(pwd)
          cd ..

      - name: Upload to s_singapore1
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          server: ${{ secrets.SSH_SERVER_ORION_SINGAPORE }}
          username: ${{ secrets.SSH_USERNAME }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: './dist.tar.gz'
          remote_path: /www/wwwroot/www1.hi.cn
          args: '-o ConnectTimeout=5'

      - name: Upload to s_chengdu1
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          server: ${{ secrets.SSH_SERVER_ORION_CHINA_CHENGDU }}
          username: ${{ secrets.SSH_USERNAME }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: './dist.tar.gz'
          remote_path: /www/wwwroot/www1.hi.cn
          args: '-o ConnectTimeout=5'

      - name: Upload to s_guangzhou1
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          server: ${{ secrets.SSH_SERVER_ORION_CHINA_GUANGZHOU }}
          username: ${{ secrets.SSH_USERNAME }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: './dist.tar.gz'
          remote_path: /www/wwwroot/www1.hi.cn
          args: '-o ConnectTimeout=5'

      - name: Uncompress zip to s_singapore1
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_SERVER_ORION_SINGAPORE }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /www/wwwroot/www1.hi.cn
            tar -xzvf dist.tar.gz
            rm -rf dist.tar.gz

      - name: Uncompress zip to s_chengdu1
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_SERVER_ORION_CHINA_CHENGDU }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /www/wwwroot/www1.hi.cn
            tar -xzvf dist.tar.gz
            rm -rf dist.tar.gz

      - name: Uncompress zip to s_guangzhou1
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_SERVER_ORION_CHINA_GUANGZHOU }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /www/wwwroot/www1.hi.cn
            tar -xzvf dist.tar.gz
            rm -rf dist.tar.gz

      - name: Enable latest build to s_singapore1
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_SERVER_ORION_SINGAPORE }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /www/wwwroot/www1.hi.cn
            rm -rf index.html
            mv index2.html index.html
            cd ..

      - name: Enable latest build to s_chengdu1
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_SERVER_ORION_CHINA_CHENGDU }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /www/wwwroot/www1.hi.cn
            rm -rf index.html
            mv index2.html index.html
            cd ..

      - name: Enable latest build to s_guangzhou1
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_SERVER_ORION_CHINA_GUANGZHOU }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /www/wwwroot/www1.hi.cn
            rm -rf index.html
            mv index2.html index.html
            cd ..
